### ISSUE TITLE
Moving resets attack range bonus set with buff

### ISSUE THREAD

**Issue by Gistix** [LeagueSandbox/GameServer#1019]
With either BaseBonus or FlatBonus issuing a move command resets AA range to its default value, can be tested with Aatrox's R

**Comment by danil179** [comment]
Related #1011 

Probably due to unimplemented channeling, and so moving will deactivate every buff with ` "CantCancelWhileChanneling": "0"`.

**Comment by ATypescriptEnjoyer** [comment]
This is correct, because its set to 0 it gets added to this list:

https://github.com/LeagueSandbox/GameServer/blob/b0217437de10dbcdecea561d34621f94b16b50b2/GameServerLib/API/ApiEventManager.cs#L163

Then when the champion moves, the deactivatebuff gets published by the server to everyone causing it to remove:

https://github.com/LeagueSandbox/GameServer/blob/b0217437de10dbcdecea561d34621f94b16b50b2/GameServerLib/API/ApiEventManager.cs#L180-L189

I don't think this is fixable until channelling is implemented, or we can just set the boolean to true for now? What do you think @danil179

**Comment by danil179** [comment]
Let me add a comment from the PR on how I think it should be implemented:
"
Following our discussion, I recommend you to check the following parameters from the json files:
`CanMoveWhileChanneling` - 1 if we should allow moving while channeling (default should be 0)
`CantCancelWhileChanneling` - 0 if we can cancel after we started channeling

The channel duration is currently not presented in the jsons, and should be added. Till it get added, I'm fine with hardcoded numbers with comment that the parameters can be found.
"

**Comment by cntseesharp** [comment]
@danil179 channel duration is actually presented, like in Xerath Q for example - `"ChannelDuration": 3,`

**Comment by lzardy** [comment]
Resolved by #1267
