### ISSUE TITLE
Skillshots hitboxes broken

### ISSUE THREAD

**Issue by cabeca1143** [LeagueSandbox/GameServer#1315]
Skillshot's hitbox detection is messed up somewhere.
I haven't investigated when this issue started, but i assume it was in one of the recent objectmanager updates.
https://youtu.be/-gv92zwbZsw

**Comment by Killfrra** [comment]
I believe the break occurred when the collision was last updated.
First part of the video: e9fb3ba5ce07ab884329a4443b11d0675c3d927e
Second part of the video: 2816faa36d3bf2f7c231058127444dcc9e93c190
https://youtu.be/CcQ8r_vKNBw
**upd.** And it's weird because the collision radius has actually doubled.
**upd.** I also had to downgrade https://github.com/LeagueSandbox/LeaguePackets/commit/f51efafbbf15a508f05b3f6e487520a4f80a8de5 by `reset`ting them `--hard` in order to build the server.
