### ISSUE TITLE
Ezreal Ult isnt synchronized

### ISSUE THREAD

**Issue by DeudlyYT** [LeagueSandbox/GameServer#146]
When you use R of Ezreal appears 2 ults:
- One is generated by the client and doesnt do damage
- The other is the projectile generated by the server

**Comment by MythicManiac** [comment]
This has been fixed according to @FurkanS1821, so closing

**Comment by MythicManiac** [comment]
Not fixed according to @joaquin95, so re-opening. Confirming the status of this would be appreciated.

**Comment by Fighter19** [comment]
Currently I found that pressing another ability while channeling the ult makes the ultimate appear on the client side instantly, but the impact itself is still the one after the channeling time.
So from what I can tell, there is only 1 ult displayed, which is the one generated at client side.

**Comment by FurkanS1821** [comment]
@Fighter19 thats because of the old bug which if you cast spell while channeling other spell, other one will be cast instantly, It was the cause of the insta-recall bug appeared a while ago, but it was unknown back then. The projectile in game is just visible and server will fire the true ult as true cast time is over.

**Comment by DeudlyYT** [comment]
Closing this as it was solved long time ago
