### ISSUE TITLE
Replace Laser system

### ISSUE THREAD

**Issue by FurkanS1821** [LeagueSandbox/GameServer#566]
The current way lasers work are:
- Draw a rectangle
- Check if things are in this rectangle
- Do things

This causes:
- The requirement of a different class
- Missing a few targets / including a few non-targets because of floating point errors
- Lag server
- Spaghetti code

We can do the same thing by:
- Creating a regular projectile
- Move it to the end in the same tick slowly until it reaches it
- Do things

**Comment by MythicManiac** [comment]
Rectangle does sound like a more proper approach here, any clue what causes the mentioned issues?

**Comment by FurkanS1821** [comment]
@MythicManiac Calculations take very long and floating point errors make things inaccurate.

**Comment by MythicManiac** [comment]
Sounds like there's some engine fundamentals wrong here in that case. What this is suggesting sounds a lot like Sphere Casting:

![image](https://user-images.githubusercontent.com/8225825/41935195-7ee108f2-7991-11e8-9883-2d7c87bf1bf0.png)

There are some "proper" really mathy ways to implement raycasting that don't take as big of  a toll on performance as how you'll likely go about it here, by just looping several steps within the "laser" and checking for collision each step. I don't believe there's an easy way for us to implement the mathy ways due to lacking support in some parts of the engine, and also lacking skills of developers, so feel free to implement it this way. Just need to ensure there's some proper max range limits in place (e.g. distance between the map's opposing edges), to avoid too much performance loss.

Of course, if you're interested, you can always look up how raycasting/sphere casting is usually done more efficiently and use those methods.

**Comment by FurkanS1821** [comment]
I had implemented the current rectangular Laser system by researching all the maths and I don't hesitate to do the same again.

**Comment by lzardy** [comment]
Resolved by #1113 and #1209.
