### ISSUE TITLE
xcopy doesn't remove deleted files

### ISSUE THREAD

**Issue by FurkanS1821** [LeagueSandbox/GameServer#646]
i.e. if file "x" is already copied to the build folder, and in the next build, that file is deleted, it still remains in the build folder and causes problems if that deleted file is a script.

**Comment by MatthewFrench** [comment]
Easy idea that could improve performance:
Remove Xcopy for scripts. Have the gameserver config point to the script content location.
Removes delay on copy and checking if all scripts are there. Also reduces hard drive space needed.

**Comment by MythicManiac** [comment]
> Remove Xcopy for scripts. Have the gameserver config point to the script content location.

As discussed in Discord, this has more or less been on the roadmap for a while. The way we should go about this is implementing the use of the content packs serverside as well, where each "bundle" of scripts/content is in a .zip file. The server should also take in a parameter of where to look content packs from (and which of them to load), instead of assuming they are in it's current directory. This way we can avoid copying anything around altogether.

**Comment by FurkanS1821** [comment]
This was gotten rid of.
