### ISSUE TITLE
lockstep or state sync? 

### ISSUE THREAD

**Issue by Kiddinglife** [LeagueSandbox/GameServer#741]
Hi there,
Do you use lockstep or state sync?
Regards.

**Comment by FurkanS1821** [comment]
Our goal is to use what LoL was using in 4.20.

Since I don't know the said terms in detail, I will tell you what I know about (original, not our) LoL server. These information might be wrong:
- Server sends a `SyncId` with every packet to clients.
- Server somehow (probably using heartbeats) uses these `SyncId`s to send packets that were lost in the process. Clients also reject packets that have been "expired".

Player positions are only updated when:
- Player casts spells
- When their path changes (client moves them along the path without server prompts if it hasn't changed)
- When they reappear out of FoW (client doesn't receive positions of invisible enemies)

I don't know how real LoL servers work but, **our server** runs on 60FPS and user inputs take effect immediately, without waiting for the next server tick.

**Comment by MythicManiac** [comment]
Closing this issue as it's a question and not an actual issue. In the future, please join our Discord server for any questions you might have.
