### ISSUE TITLE
Fog of war is behaving weird or too small

### ISSUE THREAD

**Issue by P-Kito** [LeagueSandbox/GameServer#972]
When connecting to a game and standing on middle lane, once minions appear you can only see them really really late, literally when they are standing right next to you.

**Comment by lzardy** [comment]
This issue is not because of server-side vision, this is mostly due to incorrect pathing or movements that lane minions use.

The reason you see the minions late is because the client is trying to compensate by simulating their expected position, but once they get in vision, the server sends the packet that spawns the minion and it ends up "teleporting" to its true position.
You can see the client-sided position of the minions slightly after they enter vision, which is much farther behind the server-side position.

**Comment by MatthewFrench** [comment]
Thank you for writing this. This is fantastic knowledge.

**Comment by P-Kito** [comment]
@microsoftv You will fix the packets confirmed? :-P :-P 
 I have seen someone on discord who fixed it. ming_saber#4679 I think... maybe he has a fix?

**Comment by danil179** [comment]
Partially fixed. The vision is much better now but THERE ARE still teleportation issues, mainly when you have no vision on an enemy minion, you see an "illusion" at the spawn location.
